import { render, screen } from '@testing-library/react';
import { userEvent } from '@testing-library/user-event';
import UncontrolledForm from '@/components/UncontrolledForm';
import { Provider } from 'react-redux';
import { store } from '@/store/store.ts';
import { mockUserFormFill } from './test-utils/MockUserFormFill';
import {
  TEST_FIELDS_INPUTS,
  TEST_VALIDATION_ERROR,
  TEST_VALIDATION_TESTID,
} from './test-utils/constants';

describe('UncontrolledForm', () => {
  test.each(
    // prettier-ignore
    [
    [{ NAME: TEST_FIELDS_INPUTS.NAME.EMPTY }, TEST_VALIDATION_ERROR.NAME.EMPTY, TEST_VALIDATION_TESTID.NAME],
    [{ NAME: TEST_FIELDS_INPUTS.NAME.VALID }, TEST_VALIDATION_ERROR.NAME.VALID, TEST_VALIDATION_TESTID.NAME],
    [{ NAME: TEST_FIELDS_INPUTS.NAME.SHORT }, TEST_VALIDATION_ERROR.NAME.SHORT, TEST_VALIDATION_TESTID.NAME],
    [{ NAME: TEST_FIELDS_INPUTS.NAME.LOWERCASE }, TEST_VALIDATION_ERROR.NAME.LOWERCASE, TEST_VALIDATION_TESTID.NAME], 
    [{ NAME: TEST_FIELDS_INPUTS.NAME.SYMBOLS }, TEST_VALIDATION_ERROR.NAME.SYMBOLS, TEST_VALIDATION_TESTID.NAME],
    [{ EMAIL: TEST_FIELDS_INPUTS.EMAIL.EMPTY }, TEST_VALIDATION_ERROR.EMAIL.EMPTY, TEST_VALIDATION_TESTID.EMAIL],
    [{ EMAIL: TEST_FIELDS_INPUTS.EMAIL.VALID }, TEST_VALIDATION_ERROR.EMAIL.VALID, TEST_VALIDATION_TESTID.EMAIL],   
    [{ EMAIL: TEST_FIELDS_INPUTS.EMAIL.INVALID.EMPTY_LOCAL }, TEST_VALIDATION_ERROR.EMAIL.INVALID.EMPTY_LOCAL, TEST_VALIDATION_TESTID.EMAIL],
    [{ EMAIL: TEST_FIELDS_INPUTS.EMAIL.INVALID.TWO_AT }, TEST_VALIDATION_ERROR.EMAIL.INVALID.TWO_AT, TEST_VALIDATION_TESTID.EMAIL],
    [{ EMAIL: TEST_FIELDS_INPUTS.EMAIL.INVALID.TWO_DOTS }, TEST_VALIDATION_ERROR.EMAIL.INVALID.TWO_DOTS, TEST_VALIDATION_TESTID.EMAIL],
    [{ AGE: TEST_FIELDS_INPUTS.AGE.EMPTY }, TEST_VALIDATION_ERROR.AGE.EMPTY, TEST_VALIDATION_TESTID.AGE],
    [{ AGE: TEST_FIELDS_INPUTS.AGE.VALID }, TEST_VALIDATION_ERROR.AGE.VALID, TEST_VALIDATION_TESTID.AGE],
    [{ AGE: TEST_FIELDS_INPUTS.AGE.NEGATIVE }, TEST_VALIDATION_ERROR.AGE.NEGATIVE, TEST_VALIDATION_TESTID.AGE],
    [{ AGE: TEST_FIELDS_INPUTS.AGE.LOWER }, TEST_VALIDATION_ERROR.AGE.LOWER, TEST_VALIDATION_TESTID.AGE],
    [{ AGE: TEST_FIELDS_INPUTS.AGE.NOT_NUMBER }, TEST_VALIDATION_ERROR.AGE.NOT_NUMBER, TEST_VALIDATION_TESTID.AGE],
    [{ AGE: TEST_FIELDS_INPUTS.AGE.HIGHER }, TEST_VALIDATION_ERROR.AGE.HIGHER, TEST_VALIDATION_TESTID.AGE],
    [{ PASSWORD: TEST_FIELDS_INPUTS.PASSWORD.EMPTY }, TEST_VALIDATION_ERROR.PASSWORD.EMPTY, TEST_VALIDATION_TESTID.PASSWORD],
    [{ PASSWORD: TEST_FIELDS_INPUTS.PASSWORD.VALID }, TEST_VALIDATION_ERROR.PASSWORD.VALID, TEST_VALIDATION_TESTID.PASSWORD],
    [{ PASSWORD: TEST_FIELDS_INPUTS.PASSWORD.SHORT }, TEST_VALIDATION_ERROR.PASSWORD.SHORT, TEST_VALIDATION_TESTID.PASSWORD],
    [{ CONFIRM_PASSWORD: TEST_FIELDS_INPUTS.CONFIRM_PASSWORD.EMPTY, PASSWORD: TEST_FIELDS_INPUTS.PASSWORD.VALID }, TEST_VALIDATION_ERROR.CONFIRM_PASSWORD.EMPTY, TEST_VALIDATION_TESTID.CONFIRM_PASSWORD],
    [{ CONFIRM_PASSWORD: TEST_FIELDS_INPUTS.CONFIRM_PASSWORD.VALID, PASSWORD: TEST_FIELDS_INPUTS.PASSWORD.VALID}, TEST_VALIDATION_ERROR.CONFIRM_PASSWORD.VALID, TEST_VALIDATION_TESTID.CONFIRM_PASSWORD],
    [{ CONFIRM_PASSWORD: TEST_FIELDS_INPUTS.CONFIRM_PASSWORD.MISSMATCH, PASSWORD: TEST_FIELDS_INPUTS.PASSWORD.VALID }, TEST_VALIDATION_ERROR.CONFIRM_PASSWORD.MISSMATCH, TEST_VALIDATION_TESTID.CONFIRM_PASSWORD],
    [{ GENDER: TEST_FIELDS_INPUTS.GENDER.EMPTY }, TEST_VALIDATION_ERROR.GENDER.EMPTY, TEST_VALIDATION_TESTID.GENDER],
    [{ GENDER: TEST_FIELDS_INPUTS.GENDER.VALID }, TEST_VALIDATION_ERROR.GENDER.VALID, TEST_VALIDATION_TESTID.GENDER],
    [{ GENDER: TEST_FIELDS_INPUTS.GENDER.INVALID }, TEST_VALIDATION_ERROR.GENDER.INVALID, TEST_VALIDATION_TESTID.GENDER],
    [{ COUNTRY: TEST_FIELDS_INPUTS.COUNTRY.EMPTY }, TEST_VALIDATION_ERROR.COUNTRY.EMPTY, TEST_VALIDATION_TESTID.COUNTRY],
    [{ COUNTRY: TEST_FIELDS_INPUTS.COUNTRY.VALID }, TEST_VALIDATION_ERROR.COUNTRY.VALID, TEST_VALIDATION_TESTID.COUNTRY],
    [{ COUNTRY: TEST_FIELDS_INPUTS.COUNTRY.INVALID}, TEST_VALIDATION_ERROR.COUNTRY.INVALID, TEST_VALIDATION_TESTID.COUNTRY],
    [{ UPLOAD: TEST_FIELDS_INPUTS.UPLOAD.VALID_JPG}, TEST_VALIDATION_ERROR.UPLOAD.VALID_JPG, TEST_VALIDATION_TESTID.UPLOAD],
    [{ UPLOAD: TEST_FIELDS_INPUTS.UPLOAD.VALID_PNG}, TEST_VALIDATION_ERROR.UPLOAD.VALID_PNG, TEST_VALIDATION_TESTID.UPLOAD],
    [{ UPLOAD: TEST_FIELDS_INPUTS.UPLOAD.INVALID_SIZE}, TEST_VALIDATION_ERROR.UPLOAD.INVALID_SIZE, TEST_VALIDATION_TESTID.UPLOAD],
    [{ TERMS: TEST_FIELDS_INPUTS.TERMS.CHECK}, TEST_VALIDATION_ERROR.TERMS.CHECK, TEST_VALIDATION_TESTID.TERMS],
    [{ TERMS: TEST_FIELDS_INPUTS.TERMS.UNCHECK}, TEST_VALIDATION_ERROR.TERMS.UNCHECK, TEST_VALIDATION_TESTID.TERMS],
  ]
  )(
    'should validate text fields input %s and show %s',
    async (input, expected, testid) => {
      const user = userEvent.setup();
      render(
        <Provider store={store}>
          <UncontrolledForm onCloseModal={vi.fn()} />
        </Provider>
      );
      await mockUserFormFill(user, input);
      const postButton = screen.getByRole('button', { name: 'Send' });
      await user.click(postButton);
      const validationError = screen.queryByTestId(testid);
      expect(validationError).toHaveTextContent(expected);
    }
  );
});
